### ISSUE TITLE
Disable configuration of icinga2-ido-pgsql via selection does not work 

### ISSUE THREAD

**Issue by lbetz** [Icinga/deb-icinga2#10]
Expected Behavior

Using the following lines

icinga2-ido-pgsql	icinga2-ido-pgsql/dbconfig-install	boolean	false
icinga2-ido-pgsql	icinga2-ido-pgsql/enable		boolean	false

by debconf-set-selections disables the configuration of the feature.

Current Behavior

Only on debian jessie: after the installation, configures still ask i.g. for a password to set.  On debian stretch, ubuntu xenial and bionic works fine.

**Comment by lazyfrosch** [comment]
You have two options to disable dbconfig-common:

* Install `dbconfig-no-thanks`, this disables dbconfig globally **(introduced in stretch)**
* Set the flags with a dbconfig-common config file `/etc/dbconfig-common/icinga2-ido-pgsql.conf`

Please to **not** set stuff with debconf, actual settings are always preseeded from the config files.

Example for contents, but be aware, the file is updated by dbconfig-common!

```
dbc_install='false'
dbc_upgrade='false'
dbc_remove='false'
```

Does that help?

**Comment by lbetz** [comment]
Not for the use with puppet.

1) dbconfig-no-thanks to disable dbconfig globally is just a workaround but not directly from puppet-icinga2 module.
2) icinga2-ido-pgsql is managed as package resource, the file icinga2-ido-pgsql.conf is included in this package. Modifying it after package installation makes no sense because it’s to late.
Managing this file is also a good solution because the directory /etc/dbconfig-common also doesn’t exist before the package was installed. And we can’t manage this directory from our puppet icinga2 module.

Any Ideas?

On Debian 9 and Ubuntu the package resource works quite fine with a response file, like

icinga2-ido-pgsql       icinga2-ido-pgsql/dbconfig-install      boolean false
icinga2-ido-pgsql       icinga2-ido-pgsql/enable                boolean false
