### ISSUE TITLE
Init scripts out of sync with Icinga 2 main repo

### ISSUE THREAD

**Issue by Crunsher** [Icinga/deb-icinga2#2]
See https://github.com/Icinga/icinga2/issues/6082

We have made changes to out init system but since we overwrite them in packaging we need to sync those changes here *sigh*

**Comment by lazyfrosch** [comment]
This is simply because Debian has a completely different sysv init scripting system than RedHat/SUSE

**Comment by lazyfrosch** [comment]
Latest changes seem not that important:
https://github.com/Icinga/icinga2/commits/master/etc/initsystem/icinga2.init.d.cmake

We should look into whats actually the problem here.

**Comment by lazyfrosch** [comment]
While it might be working, it is not the best solution...
