### ISSUE TITLE
Missing file / wrong config for latest icinga2-package

### ISSUE THREAD

**Issue by rajo** [Icinga/deb-icinga2#6]
Hi there,

I've just received the icinga2 r2.10.0-1 packages via packages.icinga.org and hit a nasty bug as far as I can see, as the service fails a restart after installing:

```
root@server:~# service icinga2 restart
Job for icinga2.service failed. See 'systemctl status icinga2.service' and 'journalctl -xn' for details.

```
this seems to be caused by either a wrong icinga2.service file for systemd or a missing file - don't know what the expected correct state is.

```
root@server:~# systemctl status icinga2.service
...
Oct 12 09:06:43 server systemd[1]: Failed to load environment files: No such file or directory
...

```
```
root@server:~# less /etc/systemd/system/multi-user.target.wants/icinga2.service
[Service]
Type=simple
UMask=0007
EnvironmentFile=/usr/lib/icinga2/icinga2
```

the above mentioned file does not exist, hence restarting/installing wil fail:

```
root@server:/usr/lib/icinga2# ls
prepare-dirs  safe-reload

```

Edit: Encountered only on Debian 8.

**Comment by mphilipps** [comment]
I was just looking for a bug report.. you were about 30 seconds faster.

**Comment by mphilipps** [comment]
Workaround:
Create a systemd drop-in 

> /etc/systemd/system/icinga2.service.d$ cat 10-icinga2.conf 

```
[Service]
EnvironmentFile=
ExecStartPre=
ExecStartPre=/usr/lib/icinga2/prepare-dirs /etc/default/icinga2
```

**Comment by taladar** [comment]
ExecReload also has to be changed in the drop-in

**Comment by mphilipps** [comment]
Correct. I have updated the comment.

**Comment by dnsmichi** [comment]
On a Debian Stretch container, it seems that init.d is preferred and the sysconfig file is installed to /etc/default/icinga2 instead.

@lazyfrosch Could this be the problem with supporting two init systems at once on Jessie and Stretch? (which is a mess imho)

```
root@d791ef498f76:/# cat /etc/default/icinga2
# default settings for icinga2's initscript

#DAEMON_ARGS="-e /var/log/icinga2/icinga2.err"
```

**Comment by lazyfrosch** [comment]
@dnsmichi It is normal for Ubuntu to support both, and use systemd only when booted through systemd, which is not good inside a Docker container...

I just upgraded my 2 stretch machines, my jessie machine is having the same problem.

For jessie the systemd updates for 2.10 where left out, no good. Will fix this and push an update for jessie.

**Comment by dnsmichi** [comment]
Okidoki, thanks a lot for looking 👍 

![awespme](https://media.giphy.com/media/mXnO9IiWWarkI/giphy.gif)

**Comment by lazyfrosch** [comment]
This will be fixed in 2.10.0-2 for Debian jessie (d699f42601841eb2e1201e213658b80d4e2901d7)

Build is running and will soon hit the repository.

**Comment by z0n** [comment]
I still have this issue in an Ubuntu 16.04 container. I'm using the xenial repo:
`deb http://packages.icinga.com/ubuntu icinga-xenial main`

```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 16.04.5 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-139-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 409e1113863b

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid```

**Comment by lazyfrosch** [comment]
This bug was about a missing change to the jessie packaging definition.

Ubuntu Xenial builds are based on slightly different files.

Please explain your problem with a new issue and we'll try to help. Also make sure to include error messages...

**Comment by z0n** [comment]
I already deleted my original post but you were faster :smile: I already figured out the issue, it was an error on my side. I had an override for the systemd daemon installed on the machine which included the error mentioned above.

**Comment by lazyfrosch** [comment]
@z0n Please do not simply delete, we get e-mails for your posts :wink:
